/*INSERCIÓN DE DATOS DE PRUEBA*/
--INSERT INTO alumnos (apellido,curso,fecha_nac,nombre) VALUES('Triguero','2 Daw','1992-05-17','Jesus');
--INSERT INTO alumnos (apellido,curso,fecha_nac,nombre) VALUES('Garcia','2 Daw','1992-12-06','Manuel');
--INSERT INTO alumnos (apellido,curso,fecha_nac,nombre) VALUES('Fernandez','3 ESO','1992-12-06','Alba');
--INSERT INTO alumnos (apellido,curso,fecha_nac,nombre) VALUES('Morillo','2 ESO','1992-12-06','Rocio');
--INSERT INTO alumnos (apellido,curso,fecha_nac,nombre) VALUES('Triguero','2 Daw','1992-05-17','Jesus');
--INSERT INTO alumnos (apellido,curso,fecha_nac,nombre) VALUES('Garcia','2 Daw','1992-12-06','Manuel');
--INSERT INTO alumnos (apellido,curso,fecha_nac,nombre) VALUES('Fernandez','3 ESO','1992-12-06','Alba');
--INSERT INTO alumnos (apellido,curso,fecha_nac,nombre) VALUES('Morillo','2 ESO','1992-12-06','Rocio');
--INSERT INTO alumnos (apellido,curso,fecha_nac,nombre) VALUES('Triguero','2 Daw','1992-05-17','Jesus');
--INSERT INTO alumnos (apellido,curso,fecha_nac,nombre) VALUES('Garcia','2 Daw','1992-12-06','Manuel');
--INSERT INTO alumnos (apellido,curso,fecha_nac,nombre) VALUES('Fernandez','3 ESO','1992-12-06','Alba');
--INSERT INTO alumnos (apellido,curso,fecha_nac,nombre) VALUES('Morillo','2 ESO','1992-12-06','Rocio');
